# -*- coding: utf-8 -*-
"""password_generator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-afLTGqCLJ-NpY1liPCLn4mYM9ulhaIM
"""

import random

from string import digits
from string import punctuation
from string import ascii_letters

symbols = ascii_letters + digits + punctuation
secure_random = random.SystemRandom()
password = "".join(secure_random.choice(symbols)
for i in range(20))

print(password)